#!/usr/bin/env bash


nix-shell ./default.nix -A shells.ghcjs --add-root ./dist-ghcjs/gc-roots/gc-root --indirect --run "cabal --project-file=$DIR/cabal.project --builddir=dist-ghcjs $(printf "%q " "$@")"
